brand:
  name: TechVizions
menu-string: Menu

nav:
  - title: Services
    url: '/#services'
  - title: Federal Buyers
    url: '/federal-buyers/'
  - title: Past Performance
    url: '/#portfolio'
#  - title: About
#    url: '#about'
#  - title: Team
#    url: '#team'
  - title: Contact
    url: '/#contact'

copyright: Copyright &copy; TechVizions LLC 2026

social-buttons:
  - icon: fab fa-linkedin
    url: 'https://www.linkedin.com/company/techvizions-consulting/'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fas fa-times'
  close-string: 'Close Project'
